# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.AddField(
            model_name='server',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strata.Customer'),
        ),
        migrations.AddField(
            model_name='server',
            name='environment',
            field=models.CharField(choices=[('dev', 'Development'), ('test', 'Test'), ('uat', 'UAT'), ('live', 'Live')], default='dev', max_length=10),
        ),
        migrations.AddField(
            model_name='server',
            name='weblogic_port',
            field=models.IntegerField(default=1700),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
