# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strata', '0002_auto_20170409_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strata.Customer'),
        ),
    ]
