# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strata', '0003_auto_20170409_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='weblogic_port',
            new_name='adminserver_port',
        ),
        migrations.AddField(
            model_name='server',
            name='adminserver_password',
            field=models.CharField(default='weblogic', max_length=64),
        ),
        migrations.AddField(
            model_name='server',
            name='adminserver_username',
            field=models.CharField(default='weblogic', max_length=64),
        ),
    ]
