# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strata', '0004_auto_20170409_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='strata.Server'),
            preserve_default=False,
        ),
    ]
