# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strata', '0005_auto_20170409_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='server',
        ),
        migrations.AddField(
            model_name='server',
            name='customer',
            field=models.ManyToManyField(to='strata.Customer'),
        ),
    ]
